/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package propiedades01;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Manuel
 */
public class CompRestringida extends javax.swing.JPanel {

    private String restringida;
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);
    private transient final VetoableChangeSupport vetoableChangeSupport = new VetoableChangeSupport(this);
    
    public static final String PROP_RESTRINGIDA = "restringida";

    public String getRestringida() {
        return restringida;
    }

    public void setRestringida(String restringida) throws PropertyVetoException {
        String oldRestringida = this.restringida;
        vetoableChangeSupport.fireVetoableChange(PROP_RESTRINGIDA, oldRestringida, restringida);
        this.restringida = restringida;
        this.dato.setText(restringida);
        propertyChangeSupport.firePropertyChange(PROP_RESTRINGIDA, oldRestringida, restringida);
    }


    public void addPropertyChangeListener(PropertyChangeListener listener) {
        if(propertyChangeSupport!=null)
            propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    public void addVetoableChangeListener(VetoableChangeListener listener) {
        if(vetoableChangeSupport !=null)
            vetoableChangeSupport.addVetoableChangeListener(listener);
    }

    public void removeVetoableChangeListener(VetoableChangeListener listener) {
        vetoableChangeSupport.removeVetoableChangeListener(listener);
    }


    public CompRestringida() {
        initComponents();
        
        
        ActionListener li = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    setRestringida(dato.getText());
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(CompRestringida.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        dato.addActionListener(li);
        
    }

    public String getDato() {
        return dato.getText();
    }

    public void setDato(String dato) {
        this.dato.setText(dato);
    }

    public String getTitulo() {
        return titulo.getText();
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();

        setForeground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        titulo.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        add(titulo, gridBagConstraints);

        dato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(dato, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void datoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dato;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
