/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package propiedades01;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;


/**
 *
 * @author Manuel
 */
public class SimpleRestringida extends javax.swing.JPanel {

    private String valorCompRestr;
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);
    private transient final VetoableChangeSupport vetoableChangeSupport = new VetoableChangeSupport(this);
    
    public static final String PROP_VALORCOMPRESTR = "valorCompRestr";

    public String getValorCompRestr() {
        return valorCompRestr;
    }

    public void setValorCompRestr(String valorCompRestr) throws PropertyVetoException {
        String oldValorCompRestr = this.valorCompRestr;
        vetoableChangeSupport.fireVetoableChange(PROP_VALORCOMPRESTR, oldValorCompRestr, valorCompRestr);
        this.valorCompRestr = valorCompRestr;
        this.dato.setText(valorCompRestr);
        propertyChangeSupport.firePropertyChange(PROP_VALORCOMPRESTR, oldValorCompRestr, valorCompRestr);
    }

   

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        if(propertyChangeSupport!=null)
            propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    

    public void addVetoableChangeListener(VetoableChangeListener listener) {
        if(vetoableChangeSupport!=null)
            vetoableChangeSupport.addVetoableChangeListener(listener);
    }

    public void removeVetoableChangeListener(VetoableChangeListener listener) {
        vetoableChangeSupport.removeVetoableChangeListener(listener);
    }

    
    public SimpleRestringida() {
        initComponents();
    }

    /*public String getDato() {
        return dato.getText();
    }

    public void setDato(String dato) {
        this.dato.setText(dato);
    }*/

    public String getTitulo() {
        return titulo.getText();
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        dato = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        titulo.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        add(titulo, gridBagConstraints);

        dato.setBackground(new java.awt.Color(255, 255, 255));
        dato.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(dato, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dato;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
