/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package propiedades01;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Manuel
 */
public class TxtPropCompartida extends javax.swing.JPanel {

    private String compartida;
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);
    public static final String PROP_COMPARTIDA = "compartida";

    public String getCompartida() {
        return compartida;
    }

    public void setCompartida(String compartida) {
        String oldCompartida = this.compartida;
        this.compartida = compartida;
        propertyChangeSupport.firePropertyChange(PROP_COMPARTIDA, oldCompartida, compartida);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        if(propertyChangeSupport !=null)
            propertyChangeSupport.addPropertyChangeListener(listener);
        
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    
    public TxtPropCompartida() {
        initComponents();
    }

    public String getDato() {
        return dato.getText();
    }

    public void setDato(String dato) {
        this.dato.setText(dato);
    }

    public String getTitulo() {
        return titulo.getText();
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        titulo.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        add(titulo, gridBagConstraints);

        dato.setText("jTextField1");
        dato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                datoFocusLost(evt);
            }
        });
        dato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(dato, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void datoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoActionPerformed
        setCompartida(this.getDato());
    }//GEN-LAST:event_datoActionPerformed

    private void datoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datoFocusLost
        setCompartida(this.getDato());
    }//GEN-LAST:event_datoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dato;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
