/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package compevento01;

import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author Manuel
 */
public class CompEvent01 extends javax.swing.JPanel implements Serializable {

    private ArrayList<CompEvent01Listener> lista = new ArrayList();
    
    /**
     * Creates new form CompEvent01
     */
    public CompEvent01() {
        initComponents();
    }

    public String getTexto() {
        return texto.getText();
    }

    public void setTexto(String texto) {
        this.texto.setText(texto);
    }

    public String getTitulo() {
        return titulo.getText();
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }

    public void addCompEvent01Listener(CompEvent01Listener lis){
       if(lista!=null) lista.add(lis);
    }

    public void removeCompEvent01Listener(CompEvent01Listener lis){
       lista.remove(lis);
    }
    
    public void fireCompEvent01Listener(ObjetoEvento ev){
        for(CompEvent01Listener miLis : lista){
            miLis.respuesta(ev);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        titulo.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        add(titulo, gridBagConstraints);

        texto.setColumns(20);
        texto.setRows(5);
        texto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(texto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.weighty = 1.1;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void textoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoFocusLost
        
        ObjetoEvento ev = new ObjetoEvento(texto.getText());
        fireCompEvent01Listener(ev);
        
        
    }//GEN-LAST:event_textoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
